[build]
  command = "npm run build && npm run export"
  publish = "out"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_EMAILJS_USER_ID,NEXT_PUBLIC_EMAILJS_SERVICE_ID,NEXT_PUBLIC_EMAILJS_TEMPLATE_ID"
  NEXT_PUBLIC_EMAILJS_USER_ID = "ZZnQborYt46FJ8veQ"
  NEXT_PUBLIC_EMAILJS_SERVICE_ID = "your_service_id"
  NEXT_PUBLIC_EMAILJS_TEMPLATE_ID = "your_template_id"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
