[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_CACHE_ENABLED = "true"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_EMAILJS_USER_ID,NEXT_PUBLIC_EMAILJS_SERVICE_ID,NEXT_PUBLIC_EMAILJS_TEMPLATE_ID"
  NEXT_PUBLIC_EMAILJS_USER_ID = "ZZnQborYt46FJ8veQ"
  NEXT_PUBLIC_EMAILJS_SERVICE_ID = "service_8rihs2t"
  NEXT_PUBLIC_EMAILJS_TEMPLATE_ID = "template_bn97bjx"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"